name: marine_contracts
description: A professional boat sale contract management application with Firebase integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.3
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.5.6

  # State Management
  provider: ^6.1.1

  # UI/UX
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Signature
  signature: ^5.4.1
  
  # File Handling
  file_picker: ^6.1.1
  
  # Image Handling
  image_picker: ^1.0.5
  
  # Utilities
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # For web file download
  universal_html: ^2.2.4

flutter:
  uses-material-design: true
  
  # # Add Arabic fonts
  # fonts:
  #   - family: Almarai
  #     fonts:
  #       - asset: assets/fonts/Almarai-Regular.ttf
  #       - asset: assets/fonts/Almarai-Bold.ttf
  #         weight: 700
  
  # Add custom fonts if needed
  # fonts:
  #   - family: Almarai
  #     fonts:
  #       - asset: fonts/Almarai-Regular.ttf
  #       - asset: fonts/Almarai-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Almarai-Light.ttf
  #         weight: 300

  # Add any assets/images
  # assets:
  #   - assets/images/
  #   - assets/icons/