name: marine_contracts
description: A professional boat sale contract management application with Firebase integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  # firebase_storage: ^11.5.6

  # State Management
  provider: ^6.1.1

  # UI/UX
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Signature
  signature: ^5.4.1
  
  # File Handling
  file_picker: ^10.2.0
  
  # Image Handling
  image_picker: ^1.0.5
  
  # Utilities
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  
  # Connectivity
  connectivity_plus: ^6.1.4
  
  # For web file download
  universal_html: ^2.2.4
  easy_localization: ^3.0.7+1

flutter:
  uses-material-design: true
  
# Add translation files
  assets:
    - assets/lang/
  
  # Add Arabic fonts
  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
