// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdcdKy5Ztosd1gNGdJdfjeT7p5XLyhupg',
    appId: '1:1032283375110:web:3ff54195f07ebdc6d6a587',
    messagingSenderId: '1032283375110',
    projectId: 'marine-contracts-41e2e',
    authDomain: 'marine-contracts-41e2e.firebaseapp.com',
    storageBucket: 'marine-contracts-41e2e.firebasestorage.app',
    measurementId: 'G-M7VLFLJK8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ09Hs1gTLnzxeVexG5blA7YBHYLeBhr0',
    appId: '1:1032283375110:android:a2be10a6b5e7abf0d6a587',
    messagingSenderId: '1032283375110',
    projectId: 'marine-contracts-41e2e',
    storageBucket: 'marine-contracts-41e2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjlnjzzRJBZYx_sDMJl0NJAbYHOG2bGJU',
    appId: '1:1032283375110:ios:9ded2fb10d52fe11d6a587',
    messagingSenderId: '1032283375110',
    projectId: 'marine-contracts-41e2e',
    storageBucket: 'marine-contracts-41e2e.firebasestorage.app',
    iosBundleId: 'com.example.salesContractApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjlnjzzRJBZYx_sDMJl0NJAbYHOG2bGJU',
    appId: '1:1032283375110:ios:9ded2fb10d52fe11d6a587',
    messagingSenderId: '1032283375110',
    projectId: 'marine-contracts-41e2e',
    storageBucket: 'marine-contracts-41e2e.firebasestorage.app',
    iosBundleId: 'com.example.salesContractApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdcdKy5Ztosd1gNGdJdfjeT7p5XLyhupg',
    appId: '1:1032283375110:web:3fb5529aaa622e6fd6a587',
    messagingSenderId: '1032283375110',
    projectId: 'marine-contracts-41e2e',
    authDomain: 'marine-contracts-41e2e.firebaseapp.com',
    storageBucket: 'marine-contracts-41e2e.firebasestorage.app',
    measurementId: 'G-C2BGV4E3RS',
  );
}
