// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkMlM5cqhVrF7DKftd-BtIzHjw4NW_gW8',
    appId: '1:896911915796:web:752f0ede72191f77002001',
    messagingSenderId: '896911915796',
    projectId: 'marine-contracts',
    authDomain: 'marine-contracts.firebaseapp.com',
    storageBucket: 'marine-contracts.firebasestorage.app',
    measurementId: 'G-3FELPN5LQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSt_YH9vOn3IgnxsKiwI28-0lC1wmbk4w',
    appId: '1:896911915796:android:7bdf56b2aed32bc1002001',
    messagingSenderId: '896911915796',
    projectId: 'marine-contracts',
    storageBucket: 'marine-contracts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATYZnQYZkVpNenSabPkW9EhKDVXIlhq78',
    appId: '1:896911915796:ios:a5d17938868fbd31002001',
    messagingSenderId: '896911915796',
    projectId: 'marine-contracts',
    storageBucket: 'marine-contracts.firebasestorage.app',
    iosBundleId: 'com.example.salesContractApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATYZnQYZkVpNenSabPkW9EhKDVXIlhq78',
    appId: '1:896911915796:ios:a5d17938868fbd31002001',
    messagingSenderId: '896911915796',
    projectId: 'marine-contracts',
    storageBucket: 'marine-contracts.firebasestorage.app',
    iosBundleId: 'com.example.salesContractApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkMlM5cqhVrF7DKftd-BtIzHjw4NW_gW8',
    appId: '1:896911915796:web:7a4499966e8a1493002001',
    messagingSenderId: '896911915796',
    projectId: 'marine-contracts',
    authDomain: 'marine-contracts.firebaseapp.com',
    storageBucket: 'marine-contracts.firebasestorage.app',
    measurementId: 'G-KTE6ZJSD7R',
  );
}
